#!/usr/bin/env python3
"""
Generate Polar code reliability sequence (Q_N) based on Bhattacharyya parameter.
For 5G NR, the actual Q_N is defined in TS 38.212 Table 5.3.1.2-1 (N=1024).
This script uses Bhattacharyya parameter recursion for verification.

Z(W^-) = 2Z - Z^2
Z(W^+) = Z^2
Sort by Z ascending (smaller Z = more reliable) -> Q_N
"""
import os

def bhattacharyya_z(n, z0=0.5):
    """Compute Bhattacharyya parameters for N polarized channels."""
    z = [z0]
    for _ in range(n.bit_length() - 1):
        new_z = []
        for zi in z:
            new_z.append(2 * zi - zi * zi)  # W^- (less reliable)
            new_z.append(zi * zi)            # W^+ (more reliable)
        z = new_z
    return z

def generate_qn(n, outfile):
    """Generate reliability sequence Q_N and write to file."""
    log2n = n.bit_length() - 1
    z_vals = bhattacharyya_z(n)

    # Sort indices by Z descending (larger Z = less reliable)
    # Q_N[0] = least reliable, Q_N[N-1] = most reliable
    indices = list(range(n))
    indices.sort(key=lambda i: z_vals[i], reverse=True)

    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    with open(outfile, 'w') as f:
        for idx in indices:
            f.write(f"{idx}\n")

    print(f"Generated Q_N for N={n}: {outfile}")
    print(f"  5 least reliable (frozen candidates): {indices[:5]}")
    print(f"  5 most reliable (info candidates): {indices[-5:]}")

    # Also generate Verilog header
    vh_file = outfile.replace('.txt', '.vh')
    with open(vh_file, 'w') as f:
        f.write(f"// Polar reliability sequence Q_N for N={n}\n")
        f.write(f"// Generated by gen_reliability_seq.py\n")
        f.write(f"// Q_N[0] = least reliable, Q_N[{n-1}] = most reliable\n\n")
        f.write(f"localparam integer POLAR_N = {n};\n")
        f.write(f"localparam integer POLAR_LOG2N = {log2n};\n")
        f.write(f"localparam [{log2n-1}:0] Q_N [0:{n-1}] = '{{\n")
        for i, idx in enumerate(indices):
            comma = ',' if i < n - 1 else ''
            f.write(f"    {idx}{comma}\n")
        f.write("};\n")
    print(f"  Verilog header: {vh_file}")

    return indices

if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    for n in [32, 64, 128, 256, 512, 1024]:
        outfile = os.path.join(script_dir, "..", "rtl", f"q_n_{n}.txt")
        generate_qn(n, outfile)
