// Polar reliability sequence Q_N for N=32
// Generated by gen_reliability_seq.py
// Q_N[0] = least reliable, Q_N[31] = most reliable

localparam integer POLAR_N = 32;
localparam integer POLAR_LOG2N = 5;
localparam [4:0] Q_N [0:31] = '{
    0,
    1,
    2,
    4,
    8,
    16,
    3,
    5,
    6,
    9,
    10,
    17,
    12,
    18,
    7,
    20,
    11,
    24,
    13,
    19,
    14,
    21,
    22,
    25,
    26,
    28,
    15,
    23,
    27,
    29,
    30,
    31
};
